name: Manual Deplayation

on:
    workflow_call

jobs:
    deploy_js:
        runs-on: self-hosted

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: 18.x
            
            - name: Install dep
              run: npm i

            - name: Start API
              run: npm run start